"""Project vocabulary: types and errors. Depends on the standard library only."""

from ranklens.core.exceptions import (
    ConfigError,
    DataError,
    DuplicateDocumentError,
    DuplicateMetricError,
    InsufficientSampleError,
    MalformedRowError,
    MetricNotFoundError,
    MetricSpecError,
    MissingColumnError,
    MissingDependencyError,
    MissingQrelsError,
    ModelError,
    PluginWarning,
    RankLensError,
    RankLensWarning,
    SkippedRowsWarning,
    SmallSampleWarning,
    StatisticalError,
    UngroupedInputError,
    UnsortedInputError,
    UnsupportedFormatError,
    UnsupportedModelError,
)
from ranklens.core.protocols import Metric
from ranklens.core.result import (
    BootstrapInterval,
    ComparisonResult,
    ErrorSummary,
    Evaluation,
    MetricResult,
)
from ranklens.core.types import DocId, Qrels, QueryId, RankedList, SegmentKey

__all__ = [
    "BootstrapInterval",
    "ComparisonResult",
    "ConfigError",
    "DataError",
    "DocId",
    "DuplicateDocumentError",
    "DuplicateMetricError",
    "ErrorSummary",
    "Evaluation",
    "InsufficientSampleError",
    "MalformedRowError",
    "Metric",
    "MetricNotFoundError",
    "MetricResult",
    "MetricSpecError",
    "MissingColumnError",
    "MissingDependencyError",
    "MissingQrelsError",
    "ModelError",
    "PluginWarning",
    "Qrels",
    "QueryId",
    "RankLensError",
    "RankLensWarning",
    "RankedList",
    "SegmentKey",
    "SkippedRowsWarning",
    "SmallSampleWarning",
    "StatisticalError",
    "UngroupedInputError",
    "UnsortedInputError",
    "UnsupportedFormatError",
    "UnsupportedModelError",
]
